vp1:
  image: hyperledger/fabric-peer
  ports:
    - "7150:7050"
  volumes:
   - /var/run/docker.sock:/var/run/docker.sock
  environment:
    - CORE_PEER_ADDRESSAUTODETECT=true
    - CORE_VM_ENDPOINT=unix:///var/run/docker.sock
    - CORE_LOGGING_LEVEL=DEBUG
    - CORE_PEER_DISCOVERY_ROOTNODE=172.17.0.3:7051
    - CORE_PEER_ID=vp1
    - CORE_PEER_PKI_ECA_PADDR=172.17.0.2:7054
    - CORE_PEER_PKI_TCA_PADDR=172.17.0.2:7054
    - CORE_PEER_PKI_TLSCA_PADDR=172.17.0.2:7054
    - CORE_SECURITY_ENABLED=true
    - CORE_SECURITY_ENROLLID=test_vp1
    - CORE_SECURITY_ENROLLSECRET=hackathon001
#  command: peer node start --peer-chaincodedev
  command: peer node start
